### PR TITLE
add github links

### PR DESCRIPTION
**Pull request by jennybc**

### CODE REVIEW

**Comment by data-steve** [comment]
Thanks! done

**Comment by jennybc** [comment]
I think you just closed this but did not merge it. Is that your intent?

**Comment by jennybc** [comment]
I have no idea why "this branch has conflicts that must be resolved". Maybe that's why you closed! Feel free to do so again and add the links yourself 😄. I simply tried to get here from CRAN and found the link was missing.

**Comment by data-steve** [comment]
Hi Jenny,

I’m a git merge noob when it comes to merging from a non-contributor.

I’ve tried a few different github and SO resources several times but it still won’t do it. I can see this is an useful lesson to learn on a pull request that’s has minimal chance of causing bugs. So thanks in advance for your patience as I figure this out. 

I’ll confirm when it’s good on my side.

~ Steve

Sent via telepathy

**Comment by data-steve** [comment]
hey, so i've added your two links to current master, by hand, unfortunately. Because I tried so many options from github help page and SO links to do pull request, when I finally explored yours, it looked like it had things from an older version. This is probably entirely me screwing up the pull request process. 

So I'm closing it here, thanks for the contribution!

**Comment by jennybc** [comment]
If you can't merge via GitHub, yeah it is fiddly. You need to create an associated local branch, deal with the conflicts, then merge and push. Definitely not worth it for this! Usually you *can* merge through GitHub, this was just unlucky. I have no idea why this change created a conflict. Ask the dust.

**Pull request closed without merging**
